# Generated by Django 2.1.2 on 2018-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='observacoes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
